name: Linux-ARM64 5.2

on:
  schedule:
    # Every Monday morning, at 1:11 UTC
    - cron: '11 1 * * 1'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: 'ubuntu-24.04-arm'
      compiler_ref: refs/tags/5.2.1
