name: bytecode 5.2

on:
  schedule:
    # Every Monday morning, at 1:11 UTC
    - cron: '11 1 * * 1'
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler_ref: refs/tags/5.2.0
      options: 'bytecode-only'
      timeout: 240
      runparam: 'o=20,s=4096,v=0,V=1'
