name: 5.2 bytecode

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler: 'ocaml-variants.5.2.0+options,ocaml-option-bytecode-only'
      timeout: 240
