name: musl 5.1

on:
  schedule:
    # Every Sunday morning, at 2:22 UTC
    - cron: '22 2 * * 0'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler_ref: refs/tags/5.1.1
      options: musl
      timeout: 240
      runparam: 'o=20,s=4096,v=0,V=1'
