name: Linux trunk debug

on:
  schedule:
    # Every Monday morning, at 4:44 UTC
    - cron: '44 4 * * 1'
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler_ref: refs/heads/trunk
      dune_profile: 'debug-runtime'
      runparam: 's=4096,V=1'
      timeout: 240
