name: Linux RISC-V 5.2.0

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: test on risc-v
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: riscv64
          distro: ubuntu20.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          install: |
            echo "Install packages"
            apt-get update
            echo "Update done, installing packages"
            apt-get install opam zstd -y
            echo "Running opam init"
            opam init --disable-sandboxing --auto-setup --bare

          # We need an explit ocaml-beta on ancient < 2.1 opams
          run: |
            uname -m
            echo ::set-output name=uname::$(uname -m)
            opam repository add beta git+https://github.com/ocaml/ocaml-beta-repository.git
            opam update
            opam switch create default --repos beta,default --packages 5.2.0+trunk

      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "uname output ${{ steps.runcmd.outputs.uname }}"
