name: Linux 5.0.0~alpha1

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 180

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml 5.0.0~alpha1
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-base-compiler.5.0.0~alpha1
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
            alpha: https://github.com/kit-ty-kate/opam-alpha-repository.git
          opam-depext: false
          dune-cache: true

      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest -j1 --no-buffer --display=quiet
