name: musl trunk with bugfix

on:
  schedule:
    # Every Monday morning, at 2:22 UTC
    - cron: '22 2 * * 1'
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler_repository: OlivierNicole/ocaml
      compiler_ref: refs/heads/bugfix-array-sub
      options: musl
      timeout: 240
