name: Linux 5.4

on:
  schedule:
    # Every Monday morning, at 3:33 UTC
    - cron: '33 3 * * 1'
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler_ref: refs/heads/5.4
