name: macOS-intel trunk

on:
  schedule:
    # Every Monday morning, at 3:33 UTC
    - cron: '33 3 * * 1'
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: 'macos-13'
      platform: macos
      compiler_ref: refs/heads/trunk
