name: macOS-ARM64 5.0.0

on:
  schedule:
    # Every Sunday morning, at 1:11 UTC
    - cron: '11 1 * * 0'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: 'macos-14'
      platform: macos
      compiler_ref: refs/tags/5.0.0
