name: macOS-ARM64 trunk

on:
  schedule:
    # Every Monday morning, at 5:55 UTC
    - cron: '55 5 * * 1'
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: 'macos-14'
      platform: macos
      compiler_ref: refs/heads/trunk
