name: MinGW 5.3

on:
  schedule:
    # Every Monday morning, at 2:22 UTC
    - cron: '22 2 * * 1'
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml.5.3.0,ocaml-option-mingw
      compiler_git_ref: refs/heads/5.3
      timeout: 240
