name: MinGW 5.0.0 debug

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml.5.0.0,ocaml-option-mingw
      dune_profile: 'debug-runtime'
      runparam: 's=4096,v=0,V=1'
      timeout: 240
