name: MinGW bytecode trunk

on:
  schedule:
    # Every Monday morning, at 3:33 UTC
    - cron: '33 3 * * 1'
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml.5.4.0,ocaml-option-mingw,ocaml-option-bytecode-only
      compiler_git_ref: refs/heads/trunk
      timeout: 240
