name: MinGW trunk

on:
  schedule:
    # Every Monday morning, at 4:44 UTC
    - cron: '44 4 * * 1'
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      platform: mingw
      compiler_ref: refs/heads/trunk
      timeout: 240
