name: MSVC bytecode trunk

on:
  pull_request:
  push:
    branches:
      - focus-domain-spawntree
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/msvc-common.yml
    with:
      bytecodeonly: true
