name: MSVC 5.3

on:
  schedule:
    # Every Monday morning, at 2:22 UTC
    - cron: '22 2 * * 1'
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/msvc-common.yml
    with:
      compiler_ref: '5.3'
