name: Windows trunk debug

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml.5.2.0,ocaml-option-mingw
      compiler_git_ref: refs/heads/trunk
      dune_profile: 'debug-runtime'
      runparam: 'v=0,V=1'
      timeout: 240
