name: Win 5.1 debug

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml-variants.5.1.0~rc1+options+win,ocaml-option-mingw
      dune_profile: 'debug-runtime'
      runparam: 'v=0,V=1'
      timeout: 240
