name: Win bytecode 5.0.0

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml.5.0.0,ocaml-option-mingw,ocaml-option-bytecode-only
      timeout: 360
